src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->titre;
    }

    public function setTitle(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Controller/PanierController.php
<?php 

namespace App\Controller;

use App\Controller\PanierController;
use App\Repository\ArticleRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PanierController extends AbstractController
{
/**
* @Route("/panier", name="cart_index")
*/
public function index(SessionInterface $session, ArticleRepository $articleRepository)
{
    $panier = $session->get('panier', []);

    $panierwithData = [];

    foreach($panier as $id => $quantity){
        $panierwithData[] = [
        'product' =>$articleRepository->find($id),
        'quantity' => $quantity
        ];
    }
  $total = 0;
  foreach($panierwithData as $item){
      $totalItem = $item['product']->getPrix() * $item['quantity'];
      $total += $totalItem;
  }
//   dd($panierwithData);
   return $this->render('panier/index.html.twig',['items' => $panierwithData,
'total' => $total]);

}
/**
 * @Route("/panier/add/{id}", name="cart_add")
 */

 public function add($id, SessionInterface $session){
    
     
     $panier = $session->get('panier', []);
     if(!empty($panier[$id])){
          $panier[$id]++;
     }else{
        
        $panier[$id] = 1;
     }

   

     $session->set('panier', $panier);
     return $this->redirectToRoute("cart_index");
 }

 /**
*@Route("/panier/remove/{id}", name="cart_remove")
*/
public function remove($id, SessionInterface $session){
$panier = $session->get('panier', []);
if(!empty($panier[$id])){
unset($panier[$id]);
}
$session->set('panier', $panier);
return $this->redirectToRoute("cart_index");
}
/**
 *@Route("/panier/add-one-product/{id}", name="add_one_product") 
 */
 public function addOneProduct($id,SessionInterface $session){
     $panier = $session->get('panier', []);
    $key = $panier[$id];
    dd($id , $panier, $panier[$id], $key, (int) $id === $panier[$id]);
     if((int) $id === key($panier)) {
       
        $panier[$id]++;
        // dd($panier);
     }
     $session->set('panier', $panier);
     return $this->redirectToRoute("cart_index");
 }
}

templates/panier/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="bg-light p-3">
<h1>Votre panier</h1>
</div>

{% if items | length > 0 %}

<table class="table">
<thead>
<tr>
<th>Articles</th>
<th>Prix</th>
<th>Quantité</th>
<th>Total</th>
<th></th>

</tr>
</thead>
<tbody>
{% for item in items %}

<tr>
<td>{{ item.product.title }} </td>
<td>{{ item.product.prix }} </td>
<td>{{ item.quantity }} <a href="{{path('add_one_product', {'id':item.product.id})}}" class="btn btn-success btn-sm">
<i class="fas fa-plus"></i>
</a></td>

<td>{{ item.product.prix * item.quantity }}</td>
<td>
<a href="{{path('cart_remove', {'id':item.product.id})}}" class="btn btn-danger btn-sm">
<i class="fas fa-trash"></i>
</a>

</td>
</tr>
{% endfor %}
</tbody>
<tfoot>
<td colspan="3" class="text-right"> Total : 
</td>
<td>{{ total }}</td>
<td></td>
</tfoot>
</table>
{% else %} 
<p>Surprise, c'est vide !</p>
{% endif %} 

{% endblock %}
   